# Generated by Django 2.2 on 2020-10-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0007_costoadministrativo_salarioprogramatico'),
        ('modulo_gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrapartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Contrapartida',
                'verbose_name_plural': 'Contrapartida',
            },
        ),
        migrations.CreateModel(
            name='InlineContrapartida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costos_admin', models.FloatField(verbose_name='Aporte a Costos Administrativos')),
                ('salario_programatico', models.FloatField(verbose_name='Aporte a Salario Programático')),
                ('actividades_efecto_1', models.FloatField(verbose_name='Aprote a actividades Efecto 1')),
                ('actividades_efecto_2', models.FloatField(verbose_name='Aporte a actividades Efecto 2')),
                ('overhead', models.FloatField(verbose_name='Aporte a Overhead')),
                ('contrapartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartida.Contrapartida')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.OrgImplementador')),
            ],
            options={
                'verbose_name': 'Contrapartida',
                'verbose_name_plural': 'Contrapartida',
            },
        ),
    ]
