# Generated by Django 2.2 on 2020-10-29 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrapartida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlinecontrapartida',
            name='actividades_efecto_1',
        ),
        migrations.RemoveField(
            model_name='inlinecontrapartida',
            name='actividades_efecto_2',
        ),
        migrations.AddField(
            model_name='contrapartida',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inlinecontrapartida',
            name='aporte_actividades',
            field=models.FloatField(default=0, verbose_name='Aprote a actividades'),
            preserve_default=False,
        ),
    ]
