# Generated by Django 2.2 on 2020-11-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartida', '0002_auto_20201029_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinecontrapartida',
            name='aporte_actividades',
            field=models.FloatField(verbose_name='Aporte a actividades'),
        ),
    ]
