# Generated by Django 3.0.9 on 2020-10-07 19:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0002_auto_20200824_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Efecto',
                'verbose_name_plural': 'Efectos',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('anio_inicio', models.DateField()),
                ('anio_fin', models.DateField()),
                ('aliados', models.ManyToManyField(to='listas.Aliados')),
                ('financiadores', models.ManyToManyField(to='listas.Finaciadores')),
                ('org_implementador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.OrgImplementador', verbose_name='Oganización implementador')),
                ('org_socias', smart_selects.db_fields.ChainedManyToManyField(chained_field='paises', chained_model_field='pais', horizontal=True, to='listas.OrgSocias', verbose_name='Organizaciones socias clave por país')),
                ('paises', models.ManyToManyField(to='listas.Pais', verbose_name='Países metas')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('efecto', smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Efecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción de objetivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Producto')),
            ],
            options={
                'verbose_name_plural': 'Indicadores productos',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresObjetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Objetivo')),
            ],
            options={
                'verbose_name_plural': 'Indicadores objetivos',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresEfectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('efecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Efecto')),
            ],
            options={
                'verbose_name_plural': 'Indicadores efectos',
            },
        ),
        migrations.AddField(
            model_name='efecto',
            name='objetivo',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Objetivo'),
        ),
        migrations.AddField(
            model_name='efecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto'),
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('producto', smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Producto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
