# Generated by Django 3.0.9 on 2020-08-24 21:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_auto_20200824_1539'),
        ('modulo_gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='org_socias',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='paises', chained_model_field='pais', horizontal=True, to='listas.OrgSocias', verbose_name='Organizaciones socias clave por país'),
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción de objetivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresObjetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Objetivo')),
            ],
            options={
                'verbose_name_plural': 'Indicadores objetivos',
            },
        ),
        migrations.CreateModel(
            name='Efecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('objetivo', smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='nombre', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Objetivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Efecto',
                'verbose_name_plural': 'Efectos',
            },
        ),
    ]
