# Generated by Django 3.0.9 on 2020-08-24 21:51

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0002_auto_20200824_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efecto',
            name='objetivo',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Objetivo'),
        ),
        migrations.CreateModel(
            name='IndicadoresEfectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('efecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Efecto')),
            ],
            options={
                'verbose_name_plural': 'Indicadores efectos',
            },
        ),
    ]
