# Generated by Django 3.0.9 on 2020-08-24 21:57

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0003_auto_20200824_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('efecto', smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Efecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Producto')),
            ],
            options={
                'verbose_name_plural': 'Indicadores productos',
            },
        ),
    ]
