# Generated by Django 3.0.9 on 2020-08-26 14:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0005_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndObjetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='objetivo', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndicadoresObjetivos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Indicador objetivo',
                'verbose_name_plural': 'Indicadores objetivo',
            },
        ),
        migrations.CreateModel(
            name='ObjInd4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('nombre_plataforma', models.CharField(max_length=250, verbose_name='Nombre de Plataforma')),
                ('descripcion', models.TextField()),
                ('estado_plataforma', models.CharField(choices=[('No iniciado', 'No iniciado'), ('Iniciado', 'Iniciado'), ('Avanzado', 'Avanzado'), ('Cumplido', 'Cumplido')], max_length=100, verbose_name='Estado de Plataforma')),
                ('fuente', models.CharField(max_length=300)),
                ('archivo', models.FileField(upload_to='obj-indicador-4/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndObjetivos')),
            ],
            options={
                'verbose_name': 'Indicador 4',
                'verbose_name_plural': 'Indicador 4',
            },
        ),
        migrations.CreateModel(
            name='ObjInd3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('nombre_politica_regional', models.CharField(max_length=250, verbose_name='Nombre de Pólitica Regional')),
                ('descripcion', models.TextField()),
                ('estado_esfuerzo', models.CharField(choices=[('No iniciado', 'No iniciado'), ('Iniciado', 'Iniciado'), ('Avanzado', 'Avanzado'), ('Cumplido', 'Cumplido')], max_length=100, verbose_name='Estado de esfuerzo')),
                ('fuente', models.CharField(max_length=300)),
                ('archivo', models.FileField(upload_to='obj-indicador-3/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndObjetivos')),
            ],
            options={
                'verbose_name': 'Indicador 3',
                'verbose_name_plural': 'Indicador 3',
            },
        ),
        migrations.CreateModel(
            name='ObjInd2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('numero_productores', models.IntegerField(verbose_name='Número de productores')),
                ('productividad_cacao', models.FloatField(verbose_name='Productividad cacao kg/ha')),
                ('aumento_productividad_cacao', models.FloatField(verbose_name='Aumento de productividad (%)')),
                ('fuente', models.CharField(max_length=300)),
                ('archivo', models.FileField(upload_to='obj-indicador-2/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndObjetivos')),
            ],
            options={
                'verbose_name': 'Indicador 2',
                'verbose_name_plural': 'Indicador 2',
            },
        ),
        migrations.CreateModel(
            name='ObjInd1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('numero_productores', models.IntegerField(verbose_name='Número de productores')),
                ('ingreso_saf', models.FloatField(verbose_name='Ingreso de SAF USD/ha')),
                ('aumento_ingreso_saf', models.FloatField(verbose_name='Aumento de Ingreso SAF (%)')),
                ('fuente', models.CharField(max_length=300)),
                ('archivo', models.FileField(upload_to='obj-indicador-1/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndObjetivos')),
            ],
            options={
                'verbose_name': 'Indicador 1',
                'verbose_name_plural': 'Indicador 1',
            },
        ),
    ]
