# Generated by Django 3.0.9 on 2020-08-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0006_indobjetivos_objind1_objind2_objind3_objind4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objind1',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objind2',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objind3',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='objind4',
            name='obj',
        ),
        migrations.DeleteModel(
            name='IndObjetivos',
        ),
        migrations.DeleteModel(
            name='ObjInd1',
        ),
        migrations.DeleteModel(
            name='ObjInd2',
        ),
        migrations.DeleteModel(
            name='ObjInd3',
        ),
        migrations.DeleteModel(
            name='ObjInd4',
        ),
    ]
