# Generated by Django 2.2 on 2020-10-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0003_actorespoa'),
        ('modulo_gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'POA',
                'verbose_name_plural': 'POA',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresPOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_1', models.BooleanField()),
                ('semestre_2', models.BooleanField()),
                ('monto_presupuestado', models.FloatField()),
                ('monto_semestre_1', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final de I semestre')),
                ('monto_final_anio', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final del año')),
                ('fecha_finalizacion', models.DateField()),
                ('actores', models.ManyToManyField(to='listas.ActoresPOA')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Actividades')),
                ('poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.Poa')),
            ],
        ),
    ]
