# Generated by Django 2.2 on 2020-10-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadorespoa',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
