# Generated by Django 2.2 on 2020-10-15 14:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0001_initial'),
        ('poa', '0002_auto_20201012_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadorespoa',
            options={'verbose_name': 'Sub Actividad', 'verbose_name_plural': 'Sub Actividades'},
        ),
        migrations.RemoveField(
            model_name='indicadorespoa',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='indicadorespoa',
            name='indicador',
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='descripcion',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='identificador',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='insumos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='meses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=1, max_length=88),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='meses_ejecucion',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=88, null=True),
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='responsable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='poa',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Actividades'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='indicadorespoa',
            name='actores',
        ),
        migrations.AddField(
            model_name='indicadorespoa',
            name='actores',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
