# Generated by Django 2.2 on 2020-10-16 19:41

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0001_initial'),
        ('poa', '0003_auto_20201015_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesPOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Actividades')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='SubActividadesPOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('semestre_1', models.BooleanField()),
                ('semestre_2', models.BooleanField()),
                ('monto_presupuestado', models.FloatField()),
                ('monto_semestre_1', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final de I semestre')),
                ('monto_final_anio', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final del año')),
                ('insumos', models.CharField(blank=True, max_length=250, null=True)),
                ('actores', models.CharField(blank=True, max_length=250, null=True)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('meses', multiselectfield.db.fields.MultiSelectField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=88, verbose_name='Meses planificado')),
                ('meses_ejecucion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=88, null=True)),
                ('actividad_poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.ActividadesPOA')),
            ],
            options={
                'verbose_name': 'Sub Actividad',
                'verbose_name_plural': 'Sub Actividades',
            },
        ),
        migrations.RemoveField(
            model_name='poa',
            name='actividad',
        ),
        migrations.DeleteModel(
            name='IndicadoresPOA',
        ),
        migrations.AddField(
            model_name='actividadespoa',
            name='poa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.Poa'),
        ),
    ]
