# Generated by Django 2.2 on 2020-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0004_auto_20201016_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactividadespoa',
            name='monto_semestre_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al I semestre'),
        ),
    ]
