# Generated by Django 2.2 on 2020-10-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0005_auto_20201020_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poa',
            options={'verbose_name': 'Plan de actividades', 'verbose_name_plural': 'Plan de actividades'},
        ),
    ]
