# Generated by Django 2.2 on 2020-10-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_costoadministrativo_salarioprogramatico'),
        ('modulo_gerencia', '0001_initial'),
        ('poa', '0006_auto_20201021_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Funcionamiento',
                'verbose_name_plural': 'Funcionamiento',
            },
        ),
        migrations.CreateModel(
            name='InlineSalarioPragmatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_presupuestado', models.FloatField()),
                ('monto_semestre_1', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al I semestre')),
                ('monto_final_anio', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final del año')),
                ('funcionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.Funcionamiento')),
                ('salario_pragmatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.SalarioProgramatico')),
            ],
            options={
                'verbose_name': 'Costo administrativo',
                'verbose_name_plural': 'Costo administrativo',
            },
        ),
        migrations.CreateModel(
            name='InlineCostoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_presupuestado', models.FloatField()),
                ('monto_semestre_1', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al I semestre')),
                ('monto_final_anio', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final del año')),
                ('costo_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.CostoAdministrativo')),
                ('funcionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.Funcionamiento')),
            ],
            options={
                'verbose_name': 'Costo administrativo',
                'verbose_name_plural': 'Costo administrativo',
            },
        ),
    ]
