# Generated by Django 2.2 on 2020-10-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_costoadministrativo_salarioprogramatico'),
        ('poa', '0007_funcionamiento_inlinecostoadmin_inlinesalariopragmatico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InlineSalarioPragmatico',
            new_name='InlineSalarioProgramatico',
        ),
        migrations.AlterModelOptions(
            name='inlinesalarioprogramatico',
            options={'verbose_name': 'Salario Programatico', 'verbose_name_plural': 'Salario Programatico'},
        ),
    ]
