# Generated by Django 2.2 on 2020-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0009_auto_20201021_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactividadespoa',
            name='avance_semestre_1',
            field=models.TextField(blank=True, null=True, verbose_name='Avence I semestre'),
        ),
        migrations.AddField(
            model_name='subactividadespoa',
            name='avance_semestre_2',
            field=models.TextField(blank=True, null=True, verbose_name='Avence II semestre'),
        ),
        migrations.AlterField(
            model_name='subactividadespoa',
            name='monto_final_anio',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado II semestre'),
        ),
        migrations.AlterField(
            model_name='subactividadespoa',
            name='monto_semestre_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado I semestre'),
        ),
    ]
