# Generated by Django 2.2 on 2020-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0010_auto_20201027_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactividadespoa',
            name='avance_semestre_1',
            field=models.TextField(blank=True, null=True, verbose_name='Avance I semestre'),
        ),
        migrations.AlterField(
            model_name='subactividadespoa',
            name='avance_semestre_2',
            field=models.TextField(blank=True, null=True, verbose_name='Avance II semestre'),
        ),
    ]
