# Generated by Django 2.2 on 2020-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0013_auto_20201125_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinecostoadmin',
            name='ajuste',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inlinecostoadmin',
            name='total',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inlinesalarioprogramatico',
            name='ajuste',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inlinesalarioprogramatico',
            name='total',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
