# Generated by Django 3.0.9 on 2020-08-24 21:39

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliados',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='aliados'),
        ),
        migrations.AlterField(
            model_name='finaciadores',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='finaciadores'),
        ),
        migrations.AlterField(
            model_name='orgimplementador',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='organizaciones'),
        ),
        migrations.AlterField(
            model_name='orgsocias',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='org-socias'),
        ),
    ]
