# Generated by Django 2.2 on 2020-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_auto_20200824_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActoresPOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
    ]
