# Generated by Django 2.2 on 2020-10-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_actorespoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actorespoa',
            options={'verbose_name': 'Actor POA', 'verbose_name_plural': 'Actores POA'},
        ),
    ]
