# Generated by Django 2.2 on 2020-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_auto_20201015_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoFinanciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Proyecto Financiado',
                'verbose_name_plural': 'Proyectos Financiados',
            },
        ),
    ]
