# Generated by Django 2.2 on 2020-10-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_proyectofinanciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonasViajan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Persona que viaja',
                'verbose_name_plural': 'Personas que viajan',
            },
        ),
    ]
