# Generated by Django 2.2 on 2020-10-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_costoadministrativo_salarioprogramatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Fuente documentos',
                'verbose_name_plural': 'Fuente documentos',
            },
        ),
    ]
