# Generated by Django 2.2 on 2020-10-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_gerencia', '0001_initial'),
        ('listas', '0008_fuentedocumentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='InlineDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('semestre', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=2)),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Documentos')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.FuenteDocumentos')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
