# Generated by Django 2.2 on 2020-10-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0006_personasviajan'),
        ('modulo_gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.CreateModel(
            name='InlineViaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('semestre', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('gastos_boletos', models.FloatField()),
                ('gastos_combustibles', models.FloatField()),
                ('gastos_alojamiento', models.FloatField()),
                ('gastos_diarios', models.FloatField()),
                ('paises_viajan', models.ManyToManyField(to='listas.Pais')),
                ('personas_viajan', models.ManyToManyField(to='listas.PersonasViajan')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Viajes')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
    ]
