# Generated by Django 2.2 on 2020-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viajes',
            options={'verbose_name': 'Movilización', 'verbose_name_plural': 'Movilización'},
        ),
    ]
