# Generated by Django 2.2 on 2020-10-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_auto_20201026_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlineviaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='viajes/'),
        ),
        migrations.AddField(
            model_name='inlineviaje',
            name='otros_gastos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
