# Generated by Django 2.2 on 2020-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_viajes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlineviaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='viajes/', verbose_name='Informe de Viaje'),
        ),
    ]
