# Generated by Django 2.2 on 2020-10-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_gerencia', '0001_initial'),
        ('listas', '0005_proyectofinanciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_1', models.BooleanField()),
                ('semestre_2', models.BooleanField()),
                ('monto_presupuestado', models.FloatField()),
                ('monto_semestre_1', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al I semestre')),
                ('monto_final_anio', models.FloatField(blank=True, null=True, verbose_name='Monto ejecutado al final del año')),
                ('org_implementadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.OrgImplementador')),
                ('paises_influencia', models.ManyToManyField(to='listas.Pais')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.ProyectoFinanciado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProyectosFinanciados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto Financiado',
                'verbose_name_plural': 'Proyectos Financiados',
            },
        ),
        migrations.CreateModel(
            name='ProductoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=2)),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='producto-proy-financiados/')),
                ('inline_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_financiados.InlineProyecto')),
                ('paises_influencia', models.ManyToManyField(to='listas.Pais')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='inlineproyecto',
            name='proyectos_financiados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_financiados.ProyectosFinanciados'),
        ),
    ]
