# Generated by Django 2.2 on 2020-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_financiados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectosfinanciados',
            options={'verbose_name': 'Convenio de Colaboración', 'verbose_name_plural': 'Convenios de Colaboración'},
        ),
    ]
