# Generated by Django 2.2 on 2020-10-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_financiados', '0002_auto_20201026_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inlineproyecto',
            options={'verbose_name': 'Convenio', 'verbose_name_plural': 'Convenios'},
        ),
        migrations.AlterField(
            model_name='inlineproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.ProyectoFinanciado', verbose_name='Título'),
        ),
    ]
