# Generated by Django 3.0.9 on 2020-08-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objind1',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='obj-indicador-1/'),
        ),
        migrations.AlterField(
            model_name='objind1',
            name='aumento_ingreso_saf',
            field=models.FloatField(blank=True, null=True, verbose_name='Aumento de Ingreso SAF (%)'),
        ),
        migrations.AlterField(
            model_name='objind1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objind1',
            name='ingreso_saf',
            field=models.FloatField(blank=True, null=True, verbose_name='Ingreso de SAF USD/ha'),
        ),
        migrations.AlterField(
            model_name='objind1',
            name='numero_productores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de productores'),
        ),
        migrations.AlterField(
            model_name='objind2',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='obj-indicador-2/'),
        ),
        migrations.AlterField(
            model_name='objind2',
            name='aumento_productividad_cacao',
            field=models.FloatField(blank=True, null=True, verbose_name='Aumento de productividad (%)'),
        ),
        migrations.AlterField(
            model_name='objind2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objind2',
            name='numero_productores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de productores'),
        ),
        migrations.AlterField(
            model_name='objind2',
            name='productividad_cacao',
            field=models.FloatField(blank=True, null=True, verbose_name='Productividad cacao kg/ha'),
        ),
        migrations.AlterField(
            model_name='objind3',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='obj-indicador-3/'),
        ),
        migrations.AlterField(
            model_name='objind3',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objind3',
            name='estado_esfuerzo',
            field=models.CharField(blank=True, choices=[('No iniciado', 'No iniciado'), ('Iniciado', 'Iniciado'), ('Avanzado', 'Avanzado'), ('Cumplido', 'Cumplido')], max_length=100, null=True, verbose_name='Estado de esfuerzo'),
        ),
        migrations.AlterField(
            model_name='objind3',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objind3',
            name='nombre_politica_regional',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre de Pólitica Regional'),
        ),
        migrations.AlterField(
            model_name='objind4',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='obj-indicador-4/'),
        ),
        migrations.AlterField(
            model_name='objind4',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objind4',
            name='estado_plataforma',
            field=models.CharField(blank=True, choices=[('No iniciado', 'No iniciado'), ('Iniciado', 'Iniciado'), ('Avanzado', 'Avanzado'), ('Cumplido', 'Cumplido')], max_length=100, null=True, verbose_name='Estado de Plataforma'),
        ),
        migrations.AlterField(
            model_name='objind4',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objind4',
            name='nombre_plataforma',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre de Plataforma'),
        ),
    ]
