# Generated by Django 2.2 on 2020-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_indicadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indproducto1_1_1',
            name='nombre_estudio',
        ),
        migrations.RemoveField(
            model_name='indproducto1_1_2',
            name='nombre_plan',
        ),
        migrations.AddField(
            model_name='indproducto1_1_1',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='indproducto1_1_2',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indefecto1_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indefecto1_2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indefecto2_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_1_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_1_3',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_1',
            name='numero_iniciativas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_2',
            name='numero_iniciativas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_3',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_3',
            name='numero_modelos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_4',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_4',
            name='numero_ofertas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_5',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_2_5',
            name='numero_estudio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_1',
            name='numero_eventos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de eventos o iniciativas'),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_1',
            name='numero_participantes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de participantes '),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_2',
            name='numero_experiencias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_3',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_3_3',
            name='numero_actores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de actores'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_1',
            name='numero_documentos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_2',
            name='numero_documentos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_3',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_3',
            name='numero_documentos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_4',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto1_4_4',
            name='numero_estudio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto2_5_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto2_5_1',
            name='numero_comite',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto2_5_2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto2_5_2',
            name='numero_plataformas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto2_6_1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto2_6_1',
            name='numero_politica',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='indproducto2_6_2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='indproducto2_6_2',
            name='numero_politica',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='objind1',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='objind2',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='objind3',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
        migrations.AlterField(
            model_name='objind4',
            name='fuente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente'),
        ),
    ]
