# Generated by Django 2.2 on 2020-10-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo_indicadores', '0002_auto_20201009_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndProducto2_7_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('numero_politica', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('fuente', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente')),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ind-prod-2-6-2/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndProductos')),
            ],
            options={
                'verbose_name': 'Indicador 2.7.2',
                'verbose_name_plural': 'Indicador 2.7.2',
            },
        ),
        migrations.CreateModel(
            name='IndProducto2_7_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('numero_politica', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('fuente', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente')),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ind-prod-2-6-2/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndProductos')),
            ],
            options={
                'verbose_name': 'Indicador 2.7.1',
                'verbose_name_plural': 'Indicador 2.7.1',
            },
        ),
    ]
