# Generated by Django 3.0.9 on 2020-10-02 16:30

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0007_auto_20200831_1131'),
        ('monitoreo_indicadores', '0002_auto_20200831_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndEfectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='efecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndicadoresEfectos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Proyecto')),
            ],
            options={
                'verbose_name': 'Efectos',
                'verbose_name_plural': 'Efectos',
            },
        ),
        migrations.CreateModel(
            name='IndEfecto1_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('numero_empresas', models.IntegerField(blank=True, null=True, verbose_name='Número de empresas implementando MNC')),
                ('fuente', models.CharField(blank=True, max_length=300, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ind-efecto-1-2/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndEfectos')),
            ],
            options={
                'verbose_name': 'Indicador 1.2',
                'verbose_name_plural': 'Indicador 1.2',
            },
        ),
        migrations.CreateModel(
            name='IndEfecto1_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('numero_productores', models.IntegerField(blank=True, null=True, verbose_name='Número de productores adoptando BPA')),
                ('porcentaje_mujeres', models.IntegerField(blank=True, null=True, verbose_name='% de mujeres adoptando BPA')),
                ('porentaje_jovenes', models.IntegerField(blank=True, null=True, verbose_name='% de Jovenes adoptando BPA')),
                ('fuente', models.CharField(blank=True, max_length=300, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='ind-efecto-1-1/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndEfectos')),
            ],
            options={
                'verbose_name': 'Indicador 1.1',
                'verbose_name_plural': 'Indicador 1.1',
            },
        ),
    ]
