# Generated by Django 2.2 on 2020-10-29 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoreo_indicadores', '0003_indproducto2_7_1_indproducto2_7_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='indefectos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indobjetivos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indproductos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IndicadoresProductosInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('avance', models.TextField()),
                ('fuente', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente')),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='obj-indicadores/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndProductos')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresObjetivosInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('avance', models.TextField()),
                ('fuente', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente')),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='obj-indicadores/')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndObjetivos')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='IndicadoresEfectosInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('avance', models.TextField()),
                ('fuente', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título y fuente')),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='obj-indicadores/')),
                ('efecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo_indicadores.IndEfectos')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
    ]
