# Generated by Django 3.0.9 on 2020-10-02 16:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0007_auto_20200831_1131'),
        ('monitoreo_indicadores', '0003_indefecto1_1_indefecto1_2_indefectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='indefectos',
            name='efecto',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', default=1, on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Efecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indefectos',
            name='indicador',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='efecto', chained_model_field='efecto', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndicadoresEfectos'),
        ),
    ]
