# Generated by Django 3.0.9 on 2020-10-05 14:17

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gerencia', '0007_auto_20200831_1131'),
        ('monitoreo_indicadores', '0004_auto_20201002_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='indobjetivos',
            name='objetivo',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='proyecto', chained_model_field='proyecto', default=1, on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.Objetivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indobjetivos',
            name='indicador',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='objetivo', chained_model_field='objetivo', on_delete=django.db.models.deletion.CASCADE, to='modulo_gerencia.IndicadoresObjetivos'),
        ),
    ]
